Update postBuild

diff --git a/postBuild b/postBuild
--- a/postBuild
+++ b/postBuild
@@ -13,7 +13,12 @@ cp overrides.json /srv/conda/envs/notebook/share/jupyter/lab/settings/overrides.
 # Updating Jupyter Notebook configuration to allow specific origin
 echo "Updating Jupyter Notebook configuration..."
 mkdir -p /etc/jupyter/
-echo "c.NotebookApp.allow_origin = 'https://juxlauth-codingai.elearn.rwth-aachen.de'" > /etc/jupyter/jupyter_notebook_config.py
+if echo "c.NotebookApp.allow_origin = 'https://juxlauth-codingai.elearn.rwth-aachen.de'" > /etc/jupyter/jupyter_notebook_config.py; then
+  echo "Configuration successfully updated."
+else
+  echo "Failed to update configuration. Please check permissions."
+  exit 1
+fi
 
 # Installing JupyterLab Feedback extension
 echo "Installing JupyterLab Feedback extension..."
